# Generated by Django 5.2.1 on 2025-06-14 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('factors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.factors')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('link_evidencia', models.CharField(max_length=255)),
                ('ponderacion', models.IntegerField()),
                ('meta', models.IntegerField()),
                ('calificacion', models.IntegerField()),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.characteristics')),
            ],
        ),
    ]
