# Generated by Django 5.2.1 on 2025-09-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_indicator_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='link_evidencia',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='nombre',
            field=models.CharField(max_length=511),
        ),
    ]
