# Generated by Django 5.2.1 on 2025-06-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
