# Generated by Django 5.2.1 on 2025-07-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_usuario_id_logs_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
