# Generated by Django 5.2.1 on 2025-06-14 06:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='surveys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultado', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
