# Generated by Django 5.2.1 on 2025-09-18 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RenameField(
            model_name='events',
            old_name='fecha_evento',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='events',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.date(2025, 7, 3)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='tipo_evento',
            field=models.CharField(default=datetime.date(2025, 7, 3), max_length=100),
            preserve_default=False,
        ),
    ]
